/**
 *
 * @author Jay Pineda
 */

// The server provides a remote interface, and the client calls a remote 
// interface.

module ChatroomApp {
  interface Chatroom {
        long add(in long a,in long b);
        oneway void shutdown();
    };
};