package ChatroomApp;


/**
* ChatroomApp/Chatroom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chatroom.idl
* Monday, November 26, 2018 6:51:15 o'clock PM GMT-06:00
*/

public interface Chatroom extends ChatroomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Chatroom
